name: Check instalation of dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  user-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: make install
